from enum import Enum

class CertStatus(Enum):
    NOT_ISSUED = "NOT_ISSUED"
    ISSUED = "ISSUED"
    ALREADY_ISSUED = "ALREADY_ISSUED"
    EXPIRING = "EXPIRING"
    EXPIRED = "EXPIRED"
    OK = "OK"
    RENEWED = "RENEWED"
    NOT_YET_RENEWABLE = "NOT_YET_RENEWABLE"
    CERT_MISSING = "CERT_MISSING"
    KEY_MISSING = "KEY_MISSING"
    CHAIN_MISSING = "CHAIN_MISSING"
    INVALID_CERT_FILE = "INVALID_CERT_FILE"
    NOT_SUPPORTED = "NOT_SUPPORTED"
    REVOKED = "REVOKED"
